Repository ict-solutions-dev/codeigniter-freeradius, pull requests merged in 2025-02, with the labels that each got.

#18 feat: add customizable database connection settings for FreeRadius
  src/Config/FreeRadius.php
  src/Database/Migrations/2024-01-21-223112_create_radius_tables.php
  src/Models/BaseModel.php
Labels: refactor

#20 Add new attributes & fix development DBGroup
  src/Database/Migrations/2024-01-21-223112_create_radius_tables.php
  src/Enums/Attribute.php
  src/Language/en/FreeRadius.php
  src/Models/BaseModel.php
Labels: enhancement

#22 feat: Add Nas model and entity
  src/Entities/Nas.php
  src/Models/NasModel.php
Labels: enhancement, tests:run
